# Generated by Django 4.2.2 on 2023-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mytable',
            fields=[
                ('std_rollno', models.CharField(db_column='Std_RollNo', max_length=22, primary_key=True, serialize=False)),
                ('std_name', models.CharField(db_column='Std_Name', max_length=22)),
                ('std_branch', models.CharField(blank=True, db_column='Std_Branch', max_length=14, null=True)),
                ('std_course', models.CharField(db_column='Std_Course', max_length=15)),
                ('std_studyhours', models.DecimalField(blank=True, db_column='Std_StudyHours', decimal_places=2, max_digits=4, null=True)),
                ('std_marks', models.DecimalField(db_column='Std_Marks', decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'mytable',
            },
        ),
    ]
